### ISSUE TITLE
upgrade postgres

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-helm#157]
Postgres is old. It has to be upgraded to newer version

**Comment by ywkim312** [comment]
After updating the chart, then deployed. The log shows the incompatibility
```
2024-06-24 21:13:49.167 GMT [1] FATAL:  database files are incompatible with server
2024-06-24 21:13:49.167 GMT [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 16.3.```

**Comment by ywkim312** [comment]
Here's the general process
1. back up all the databases (currently, keycloak, datawolf, maestro_galveston, maestro_joplin, maestro_slc)
2. when back up, use both pgAdmin and Script, just in case
3. check updated helm chart (values.yaml, values-incore-*.yaml, passwords inside it for postgres, and other users)
4. helm dep up (check if the tar file get upgraded)
5. make zero scale for statefulsets (datawolf, keycloak)
6. delete postgres statefulset
7. delete PVC for postgres (PVC first)
8. delete PV for postgres
9. deploy the upgraded chart
10. check postgres deployment (password, check initdb was successfully performed)
11. restore backed up databases to new postgres
12. scale up for datawolf and keycloak (check the logs if it is okay)
13. check keycloak (keycloak login, incore login, incore token decode)
14. check data wolf

**Comment by ywkim312** [comment]
If you need to redo the things or trouble shooting
1. make postgres statefulset's scale to zero
2. delete PVC for postgres
3. delete PV for postgres
4. make postgres satefulset's scale to one
5. go to radiant and remove the volume that was removed on step 2

**Comment by ywkim312** [comment]
If you need to have a pod that controls the mounted volume (this might needed after postgres pod is one)
```
apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
  - name: temp-container
    image: busybox
    volumeMounts:
    - mountPath: "/mnt"
      name: postgres-volume
    command: ['sh', '-c', 'echo Container is Running; sleep 3600']
  volumes:
  - name: postgres-volume
    persistentVolumeClaim:
      claimName: postgres-pvc  # Adjust this to match your PersistentVolumeClaim
```

deploy by 
```
kubectl apply -f temp-pod.yaml
```

go inside the pod
```
kubectl exec -it temp-pod -- /bin/sh
```

to remove the pod
```
kubectl delete pod <pod-name>
```

to get the claimName 
```
kubectl get pvc -n incore
```
