### ISSUE TITLE
Add config from jupyter notebook-prod to dev and tst

### ISSUE THREAD

**Issue by Vismayak** [IN-CORE/incore-helm#93]
Quick copy paste of this
```
 extraFiles:
    pluginsettings:
      mountPath: /etc/ipython/ipython_config.py 
      stringData: |
        c = get_config()
        c.HistoryManager.hist_file=":memory:"
      mode: 0444
```
